// Travis Pochintesta
// MIU 1308
// Week 1
// json.js

var json = {
	"contact1": {
		"fname": 		 ["First Name:", "Bea"],
		"lname": 		 ["Last Name:", "O'Problem"],
		"address": 		 ["Address:", "123 Delaney Ave. Orl, FL 32806"],
		"phone":		 ["Phone:", "(407)555-6001"],
		"email":		 ["Email:", "bea@gmail.com"],
		"gender": 	   	 ["Gender:", "Female"],
		"title":		 ["Title:", "Mrs."],
		"relationship":	 ["Relationship", ["Family"]],	
		"birthday":		 ["Birthday:", "1975-07-30"],
		"bestyrating":	 ["Besty Rating:", "100"],
		"notes":		 ["Notes:", "Call for Holidays"]		
	},
	"contact2": {
		"fname": 		 ["First Name:", "Amanda"],
		"lname": 		 ["Last Name:", "Hugginkiss"],
		"address": 		 ["Address:", "2217 Orange Ave. Orl, FL 32803"],
		"phone":		 ["Phone:", "(407)555-7875"],
		"email":		 ["Email:", "hugginkiss@gmail.com"],
		"gender": 	   	 ["Gender:", "Female"],
		"title":		 ["Title:", "Mrs."],
		"relationship":	 ["Relationship", ["Family"]],
		"birthday":		 ["Birthday:", "1974-04-09"],
		"bestyrating":	 ["Besty Rating:","100"],
		"notes":		 ["Notes:", "Wife"]		
	},
	"contact3": {
		"fname": 		 ["First Name:", "Anita"],
		"lname": 		 ["Last Name:", "Bath"],
		"address": 		 ["Address:", "1220 Marsh Cove Ct. Orl, FL 32825"],
		"phone":		 ["Phone:", "(407)555-8817"],
		"email":		 ["Email:", "abath@gmail.com"],
		"gender": 	   	 ["Gender:", "Female"],
		"title":		 ["Title:", "Ms."],
		"relationship":	 ["Relationship", ["Family"]],
		"birthday":		 ["Birthday:", "2001-12-20"],
		"bestyrating":	 ["Besty Rating:","100"],
		"notes":		 ["Notes:", "Daughter"]		
	},
	"contact4": {
		"fname": 		 ["First Name:", "Ivana"],
		"lname": 		 ["Last Name:", "Tinkle"],
		"address": 		 ["Address:", "220 Pine St. Orl, FL 32807"],
		"phone":		 ["Phone:", "(407)555-8888"],
		"email":		 ["Email:", "itinkle@fullsail.com"],
		"gender": 	   	 ["Gender:", "Female"],
		"title":		 ["Title:", "Ms."],
		"relationship":	 ["Relationship", ["Family"]],
		"birthday":		 ["Birthday:", "1980-06-16"],
		"bestyrating":	 ["Besty Rating:","0"],
		"notes":		 ["Notes:", "HR"]		
	},
	"contact5": {
		"fname": 		 ["First Name:", "Ollie"],
		"lname": 		 ["Last Name:", "Tabooger"],
		"address": 		 ["Address:", "909 Simpson St. Orl, FL 32807"],
		"phone":		 ["Phone:", "(407)555-5555"],
		"email":		 ["Email:", "otabooger@gmail.com"],
		"gender": 	   	 ["Gender:", "Male"],
		"title":		 ["Title:", "Mr."],
		"relationship":	 ["Relationship", ["Acquaintance"]],
		"birthday":		 ["Birthday:", "1973-05-15"],
		"bestyrating":	 ["Besty Rating:","10"],
		"notes":		 ["Notes:", "Skater Dude"]		
	},
	"contact6": {
		"fname": 		 ["First Name:", "Ahmed"],
		"lname": 		 ["Last Name:", "Adoudi"],
		"address": 		 ["Address:", "900 Exodus Ln. Orl, FL 32822"],
		"phone":		 ["Phone:", "(407)555-9000"],
		"email":		 ["Email:", "aadoudi@fullsail.edu"],
		"gender": 	   	 ["Gender:", "Male"],
		"title":		 ["Title:", "Mr."],
		"relationship":	 ["Relationship", ["School"]],
		"birthday":		 ["Birthday:", "1986-01-20"],
		"bestyrating":	 ["Besty Rating:","20"],
		"notes":		 ["Notes:", "Study Buddy"]		
	},
	"contact7": {
		"fname": 		 ["First Name:", "Heywood U."],
		"lname": 		 ["Last Name:", "Kuddleme"],
		"address": 		 ["Address:", "3300 University Blvd. Winter Park, FL 32792"],
		"phone":		 ["Phone:", "(407)679-0100"],
		"email":		 ["Email:", "heywoodk@fullsail.com"],
		"gender": 	   	 ["Gender:", "Male"],
		"title":		 ["Title:", "Mr."],
		"relationship":	 ["Relationship", ["Work"]],
		"birthday":		 ["Birthday:", "1976-08-09"],
		"bestyrating":	 ["Besty Rating:","0"],
		"notes":		 ["Notes:", "Security"]		
	},
	"contact8": {
		"fname": 		 ["First Name:", "Maya"],
		"lname": 		 ["Last Name:", "Normusbutt"],
		"address": 		 ["Address:", "876 Oxalis Ave. Orl, FL 32807"],
		"phone":		 ["Phone:", "(407)555-1010"],
		"email":		 ["Email:", "mnormusbutt@gmail.com"],
		"gender": 	   	 ["Gender:", "Female"],
		"title":		 ["Title:", "Mrs."],
		"relationship":	 ["Relationship", ["Family"]],
		"birthday":		 ["Birthday:", "1975-05-04"],
		"bestyrating":	 ["Besty Rating:","70"],
		"notes":		 ["Notes:", "Sister In-Law"]		
	},
	"contact9": {
		"fname": 		 ["First Name:", "Yuri"],
		"lname": 		 ["Last Name:", "Nater"],
		"address": 		 ["Address:", "400 Rushing St. Orl, FL 32809"],
		"phone":		 ["Phone:", "(407)555-2020"],
		"email":		 ["Email:", "yurin@fullsail.edu"],
		"gender": 	   	 ["Gender:", "Male"],
		"title":		 ["Title:", "Mr."],
		"relationship":	 ["Relationship", ["School"]],
		"birthday":		 ["Birthday:", "1985-12-18"],
		"bestyrating":	 ["Besty Rating:","50"],
		"notes":		 ["Notes:", "Study Buddy"]		
	},
	"contact10": {
		"fname": 		 ["First Name:", "Waylon"],
		"lname": 		 ["Last Name:", "Smithers"],
		"address": 		 ["Address:", "1220 Moe St. Longwood, FL 32779"],
		"phone":		 ["Phone:", "(407)555-2222"],
		"email":		 ["Email:", "wsmithers@fullsail.com"],
		"gender": 	   	 ["Gender:", "Male"],
		"title":		 ["Title:", "Mr."],
		"relationship":	 ["Relationship", ["School"]],
		"birthday":		 ["Birthday:", "1970-11-20"],
		"bestyrating":	 ["Besty Rating:","100"],
		"notes":		 ["Notes:", "Assistant"]		
	},
	"contact11": {
		"fname": 		 ["First Name:", "Jimbo"],
		"lname": 		 ["Last Name:", "Jones"],
		"address": 		 ["Address:", "200 Deerwood Ave. Orl, FL 32822"],
		"phone":		 ["Phone:", "(407)555-6666"],
		"email":		 ["Email:", "jimbo@gmail.com"],
		"gender": 	   	 ["Gender:", "Male"],
		"title":		 ["Title:", "Mr."],
		"relationship":	 ["Relationship", ["Friend"]],
		"birthday":		 ["Birthday:", "1977-12-17"],
		"bestyrating":	 ["Besty Rating:","100"],
		"notes":		 ["Notes:", "Bff"]		
	},
	"contact12": {
		"fname": 		 ["First Name:", "Hugh"],
		"lname": 		 ["Last Name:", "Jimpostion"],
		"address": 		 ["Address:", "20 Church St. Orl, FL 32801"],
		"phone":		 ["Phone:", "(407)555-7777"],
		"email":		 ["Email:", "hjimposition@gmail.com"],
		"gender": 	   	 ["Gender:", "Male"],
		"title":		 ["Title:", "Mr."],
		"relationship":	 ["Relationship", ["Family"]],
		"birthday":		 ["Birthday:", "1979-03-14"],
		"bestyrating":	 ["Besty Rating:","20"],
		"notes":		 ["Notes:", "Cousin"]		
	},
	"contact13": {
		"fname": 		 ["First Name:", "Ura"],
		"lname": 		 ["Last Name:", "Dumas"],
		"address": 		 ["Address:", "100 Willow Ave. Orl, FL 32825"],
		"phone":		 ["Phone:", "(407)555-9222"],
		"email":		 ["Email:", "udumas@fullsail.com"],
		"gender": 	   	 ["Gender:", "Male"],
		"title":		 ["Title:", "Mr."],
		"relationship":	 ["Relationship", ["Work"]],
		"birthday":		 ["Birthday:", "1965-03-22"],
		"bestyrating":	 ["Besty Rating:","0"],
		"notes":		 ["Notes:", "Boss"]		
	},
	"contact14": {
		"fname": 		 ["First Name:", "Drew P."],
		"lname": 		 ["Last Name:", "Cheeks"],
		"address": 		 ["Address:", "220 Orange Blossom Tr. Orl, FL 32803"],
		"phone":		 ["Phone:", "(407)555-1111"],
		"email":		 ["Email:", "dpcheeks@gmail.com"],
		"gender": 	   	 ["Gender:", "Male"],
		"title":		 ["Title:", "Mr."],
		"relationship":	 ["Relationship", ["Acquaintance"]],
		"birthday":		 ["Birthday:", "1983-01-30"],
		"bestyrating":	 ["Besty Rating:","30"],
		"notes":		 ["Notes:", "Study Buddy"]		
	},
	"contact15": {
		"fname": 		 ["First Name:", "Lisa"],
		"lname": 		 ["Last Name:", "Simpson"],
		"address": 		 ["Address:", "742 Evergreen Terrace Orl, FL 32806"],
		"phone":		 ["Phone:", "(407)555-6789"],
		"email":		 ["Email:", "lisas@gmail.com"],
		"gender": 	   	 ["Gender:", "Female"],
		"title":		 ["Title:", "Ms."],
		"relationship":	 ["Relationship", ["Family"]],
		"birthday":		 ["Birthday:", "2001-12-20"],
		"bestyrating":	 ["Besty Rating:","100"],
		"notes":		 ["Notes:", "Sister"]		
	},
	"contact16": {
		"fname": 		 ["First Name:", "Milhouse"],
		"lname": 		 ["Last Name:", "Van Houten"],
		"address": 		 ["Address:", "55 Cypress Rd. Orl, FL 32827"],
		"phone":		 ["Phone:", "(407)555-0987"],
		"email":		 ["Email:", "millyv@gmail.com"],
		"gender": 	   	 ["Gender:", "Male"],
		"title":		 ["Title:", "Mr."],
		"relationship":	 ["Relationship", ["Friend"]],
		"birthday":		 ["Birthday:", "1983-10-20"],
		"bestyrating":	 ["Besty Rating:","100"],
		"notes":		 ["Notes:", "Bff"]		
	},
	"contact17": {
		"fname": 		 ["First Name:", "Nelson"],
		"lname": 		 ["Last Name:", "Muntz"],
		"address": 		 ["Address:", "400 Oak Ct. Orl, FL 32828"],
		"phone":		 ["Phone:", "(407)555-7654"],
		"email":		 ["Email:", "nmuntz@gmail.com"],
		"gender": 	   	 ["Gender:", "Male"],
		"title":		 ["Title:", "Mr."],
		"relationship":	 ["Relationship", ["Family"]],
		"birthday":		 ["Birthday:", "1979-09-11"],
		"bestyrating":	 ["Besty Rating:","20"],
		"notes":		 ["Notes:", "Brother In-Law"]		
	},
	"contact18": {
		"fname": 		 ["First Name:", "Ned"],
		"lname": 		 ["Last Name:", "Flanders"],
		"address": 		 ["Address:", "740 Evergreen Terrace Orl, FL 32806"],
		"phone":		 ["Phone:", "(407)555-3333"],
		"email":		 ["Email:", "nflanders@gmail.com"],
		"gender": 	   	 ["Gender:", "Male"],
		"title":		 ["Title:", "Mr."],
		"relationship":	 ["Relationship", ["Acquaintance"]],
		"birthday":		 ["Birthday:", "1973-02-14"],
		"bestyrating":	 ["Besty Rating:","5"],
		"notes":		 ["Notes:", "Neighbor"]		
	},
	"contact19": {
		"fname": 		 ["First Name:", "Barney"],
		"lname": 		 ["Last Name:", "Gumble"],
		"address": 		 ["Address:", "Moe's Tavern Orl, FL 32825"],
		"phone":		 ["Phone:", "(407)555-0044"],
		"email":		 ["Email:", "barneyg@gmail.com"],
		"gender": 	   	 ["Gender:", "Male"],
		"title":		 ["Title:", "Mr."],
		"relationship":	 ["Relationship", ["Friend"]],
		"birthday":		 ["Birthday:", "1972-12-02"],
		"bestyrating":	 ["Besty Rating:","100"],
		"notes":		 ["Notes:", "Bff"]		
	},
	"contact20": {
		"fname": 		 ["First Name:", "Troy"],
		"lname": 		 ["Last Name:", "McClure"],
		"address": 		 ["Address:", "101 Money St. Winter Park, FL 32790"],
		"phone":		 ["Phone:", "(407)555-5555"],
		"email":		 ["Email:", "tmcclure@gmail.com"],
		"gender": 	   	 ["Gender:", "Male"],
		"title":		 ["Title:", "Mr."],
		"relationship":	 ["Relationship", ["Work"]],
		"birthday":		 ["Birthday:", "1978-1-13"],
		"bestyrating":	 ["Besty Rating:","10"],
		"notes":		 ["Notes:", "Sales"]		
	}
}